go sdk transformer
Stark-Tech-Group/stg-sdk-golang pull request #102
Opened 2023-09-14 18:59 UTC by starkballc

# Updates
- [ TSP-6174 ] Implement transformation logic in go sdk

### Important Notes
- implemented transformation logic and tested in go sdk

2023-09-14 19:05 UTC, starkshears approved these changes, later dismissed

2023-09-14 19:55 UTC, starkshears submitted a review, later dismissed

2023-09-15 13:36 UTC, starkmichelsc requested changes

2023-09-15 13:36 UTC, starkmichelsc commented on pkg/domain/transformer.go
> +func getTransMap(s string) (map[interface{}]interface{}, error) {
the return should be a float[float] as you are parsing to a float. this well prevent a need for further casting in follow up code

2023-09-15 13:36 UTC, starkmichelsc commented on pkg/domain/msgResp.go
> +type MsgResp struct {
what is the purpsoe of this struct? It looks like the only field that is used is the value. Is this struct needed or are there plans for using the other values in later changes?

2023-09-15 13:36 UTC, starkmichelsc commented on pkg/domain/telemetry-message.go
> +	n.Values = make(map[string]float64)
values can be private given the provided Set/Get funcs

2023-09-15 13:36 UTC, starkmichelsc commented on pkg/domain/telemetry-message_test.go
> +	assert.Equal(t, value, message.Values[key])
Update to use the Getter

2023-09-15 14:12 UTC, starkmichelsc requested changes

2023-09-15 14:12 UTC, starkmichelsc commented on pkg/domain/transformer.go
> +func getTransMap(s string) (map[float64]float64, error) {
rename to parseTransMap

2023-09-15 14:12 UTC, starkmichelsc commented on pkg/domain/route.go
> +type Route struct {
please rename to something that does not conflict with route as that is used for handlers/endpoints. maybe TransformerValue? and add the float64 to this struct as you will need to convert from a iot-message-bus.Route -> this struct to use the sdk. This struct would also be used in TDS to revert to the raw value as well. "Route" is specific to iot-message-bus

2023-09-15 14:40 UTC, starkmichelsc requested changes

2023-09-15 14:40 UTC, starkmichelsc commented on pkg/domain/transformer.go
> +func Transform(telem *TelemetryMessage, route *TransformerValue) (*TelemetryMessage, error) {
this takes in a telem pointer but also returns a telem pointer. it should either
1. take in a point and only return error( alter inline)  
2. take in a non-pointer and return a non-pointer(alter and return)

rename route param. 
Does the router param need to be a pointer?

2023-09-15 14:54 UTC, starkmichelsc approved these changes

2023-09-15 14:55 UTC, starkshears approved these changes

2023-09-15 15:19 UTC, merged