feature/TSP-3007
Stark-Tech-Group/stg-sdk-golang pull request #53
Opened 2022-11-15 21:22 UTC by starkshears

# Updates
- TSP-3007 Order by support for queryParam by a single field

### Important Notes
- Added SortA and SortD fields to QueryParams struct
- BuildParameterizedQuery adds " ORDER BY [q.SortA] ASC" or "ORDER BY [q.SortD] DESC" accordingly

2022-11-15 21:23 UTC, starkmarkler submitted a review, later dismissed

2022-11-15 21:25 UTC, starkleem requested changes

2022-11-15 21:25 UTC, starkleem commented on pkg/starkapi/query-params.go
> +
Make an else statement, only one order by can exist in the query

2022-11-16 14:19 UTC, starkleem requested changes

2022-11-16 14:19 UTC, starkleem commented on pkg/starkapi/query-params.go
> +func (q *QueryParams) FindSqlColumn(t reflect.Type, sortVal string) string {
change to private (f)

2022-11-16 14:23 UTC, starkleem approved these changes

2022-11-16 14:24 UTC, starkmarkler approved these changes

2022-11-16 14:25 UTC, starksweeneym commented on pkg/starkapi/query-params.go
> +				if field.Name == "SortD" {
can it be both sortA and sortD? Otherwise this should be an else if

2022-11-16 14:25 UTC, merged